name: Build Test (Dev Branch)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: paxapos-docs-test:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test build success
        run: echo "✅ Build completado exitosamente en rama dev"
